(function(){
'use strict';
var MARKER='__SCS_COURT_CENTER__', session=null, players=[], timer=null, activeTab='waiting', editingId=null, busy=false, pendingTournamentMatch=null;
function el(id){return document.getElementById(id)}
function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
function club(){try{return typeof getMyClub==='function'?getMyClub():{id:localStorage.getItem('kbrr_org_club_id'),name:localStorage.getItem('kbrr_org_club_name')}}catch(e){return{}}}
function games(){return session&&session.rounds_data&&session.rounds_data[0]?session.rounds_data[0].games||[]:[]}
function status(g){if(g.court_center_status==='approved')return 'approved';if(g.score_status==='scored')return 'score_ready';return g.court_center_status||(g.court?'playing':'waiting')}
async function findSession(){var c=club();if(!c.id)return null;var rows=await sbGet('sessions','club_id=eq.'+c.id+'&status=eq.live&started_by=eq.'+encodeURIComponent(MARKER)+'&order=created_at.desc&limit=1&select=id,rounds_data,started_by,updated_at,club_id');return rows&&rows[0]||null}
async function createSession(){var c=club();if(!c.id)throw new Error('Select a club first.');var n=Math.max(1,parseInt(el('scsCourtCount').value,10)||1);var data={club_id:c.id,date:(typeof localDateStr==='function'?localDateStr():new Date().toISOString().slice(0,10)),started_by:MARKER,status:'live',players:[],rounds_data:[{round:1,winnerEnabled:true,courtCenter:true,numCourts:n,games:[]}],updated_at:new Date().toISOString()};var r=await sbPost('sessions',data);session=r&&r[0];return session}

/* V127: tournament-only local session; normal Court Center keeps its existing server workflow. */
var LOCAL_TM_SESSION='scs_tournament_court_session_v115';
function isLocalSession(){return !!(session&&String(session.id||'').indexOf('local-tournament-')===0)}
function readLocalSession(){try{return JSON.parse(localStorage.getItem(LOCAL_TM_SESSION)||'null')}catch(_){return null}}
function persistLocalSession(){if(isLocalSession())localStorage.setItem(LOCAL_TM_SESSION,JSON.stringify(session))}
function localScoreUpdate(sessionId,court,pair1,pair2,score,winner){
 var local=readLocalSession();if(!local||local.id!==sessionId)return false;
 var r=local.rounds_data[0],g=(r.games||[]).find(function(x){return Number(x.court)===Number(court)&&JSON.stringify(x.pair1)===JSON.stringify(pair1)&&JSON.stringify(x.pair2)===JSON.stringify(pair2)});
 if(!g)return false;
 g.score=score;g.score_status=winner?'scored':(score?'scoring':null);if(winner)g.winner=winner;
 localStorage.setItem(LOCAL_TM_SESSION,JSON.stringify(local));session=local;
 if(window.SCSTournament&&SCSTournament.renderLive)SCSTournament.renderLive();return true;
}
async function startTournament(tournament,numCourts){
 var n=Math.max(1,Math.min(20,Number(numCourts)||1));
 var old=readLocalSession();
 if(old&&old.rounds_data&&old.rounds_data[0]&&old.rounds_data[0].tournament&&old.rounds_data[0].tournament.title===tournament.title){session=old;session.rounds_data[0].numCourts=n;session.rounds_data[0].tournament=tournament;}
 else session={id:'local-tournament-'+Date.now(),started_by:MARKER,rounds_data:[{round:1,winnerEnabled:true,courtCenter:true,numCourts:n,games:[],tournament:tournament}]};
 persistLocalSession();clearInterval(timer);timer=setInterval(refreshTournamentState,2000);return liveState();
}
function liveState(){var local=readLocalSession();if(local&&(!session||!isLocalSession()))session=local;var r=session&&session.rounds_data&&session.rounds_data[0];return {ready:!!session,courtCount:courtCount(),freeCourts:freeCourts(),games:games().slice(),tournament:r&&r.tournament?r.tournament:null}}
async function resumeTournament(){var old=readLocalSession();if(!old||!old.rounds_data||!old.rounds_data[0]||!old.rounds_data[0].tournament)return null;session=old;clearInterval(timer);timer=setInterval(refreshTournamentState,2000);return liveState()}
async function refreshTournamentState(){if(!session||busy)return liveState();if(isLocalSession()){var latest=readLocalSession();if(latest){session=latest;if(window.SCSTournament&&SCSTournament.renderLive)SCSTournament.renderLive();}return liveState()}try{session=await latestSession();if(window.SCSTournament&&SCSTournament.renderLive)SCSTournament.renderLive()}catch(e){}return liveState()}
async function save(){if(!session)return;session.updated_at=new Date().toISOString();if(isLocalSession()){persistLocalSession();return}await sbPatch('sessions','id=eq.'+session.id,{rounds_data:session.rounds_data,updated_at:session.updated_at})}
function courtCount(){var r=session&&session.rounds_data&&session.rounds_data[0];return Math.max(1,Number(r&&r.numCourts)||1)}
function freeCourts(){var used=new Set(games().filter(function(g){var s=status(g);return g.court&&s!=='approved'&&s!=='waiting'}).map(function(g){return Number(g.court)}));var a=[];for(var i=1;i<=courtCount();i++)if(!used.has(i))a.push(i);return a}
function allocate(){var free=freeCourts(), waiting=games().filter(function(g){return status(g)==='waiting'});while(free.length&&waiting.length){var g=waiting.shift();g.court=free.shift();g.court_center_status='playing';g.score_status=null;}}
async function open(){var o=el('scsCourtCenterOverlay');if(!o)return;o.hidden=false;el('scsCourtClub').textContent=club().name||'Select a club';el('scsCourtBody').innerHTML='<div class="scs-court-empty">Loading…</div>';try{players=typeof dbGetPlayers==='function'?await dbGetPlayers(false):[];session=await findSession();render();}catch(e){el('scsCourtBody').innerHTML='<div class="scs-court-empty">'+esc(e.message||'Could not load Court Center')+'</div>';}clearInterval(timer);timer=setInterval(refresh,2000)}
function close(){el('scsCourtCenterOverlay').hidden=true;clearInterval(timer);timer=null}
async function refresh(){if(!session||busy||(el('scsCourtAssignForm')&&!el('scsCourtAssignForm').hidden))return;try{var rows=await sbGet('sessions','id=eq.'+session.id+'&select=id,rounds_data,started_by,updated_at,club_id');if(rows&&rows[0]){session=rows[0];render();}}catch(e){}}
function team(g,side){return (g[side]||[]).map(esc).join(' / ')}
function courtPlayerRows(pair){return (pair||[]).map(function(n){var key=String(n||'').split('#')[0].trim().toLowerCase(),p=players.find(function(x){return x&&String(x.name||'').trim().toLowerCase()===key}),female=p&&String(p.gender||'').toLowerCase().indexOf('female')>=0;return '<div class="scs-court-player"><img src="'+(female?'female.png':'male.png')+'" alt=""><b>'+esc(n)+'</b></div>'}).join('')}
function scoreText(g){var s=g.score||{},sets=Array.isArray(s.completedSets)?s.completedSets:[];if(sets.length)return sets.map(function(x){return x.score.join('–')}).join('  |  ');if(s.currentScore)return s.currentScore.join(' – ');return '–'}
function notStarted(g){return !!g&&status(g)!=='approved'&&status(g)!=='score_ready'&&!g.score&&!g.winner&&(!g.score_status||g.score_status==='waiting')}
function matchActions(g){return '<div class="scs-court-match-actions"><button type="button" onclick="SCSCourtCenter.editMatch(\''+esc(g.ccid)+'\')">Change Players</button><button type="button" class="scs-court-delete" onclick="SCSCourtCenter.deleteMatch(\''+esc(g.ccid)+'\')">Delete Match</button></div>'}
function courtCard(n){var g=games().find(function(x){return Number(x.court)===n&&status(x)!=='approved'});if(!g)return '<div class="scs-court-card court-'+n+' is-free"><div class="scs-court-head"><strong>COURT '+n+'</strong><span>FREE</span></div><p>No match assigned</p></div>';var st=status(g),label=st==='score_ready'?'SCORE READY':(g.score_status==='scoring'?'LIVE':'PLAYING');var html='<div class="scs-court-card court-'+n+' '+(st==='score_ready'?'is-ready':'')+'"><div class="scs-court-head"><strong>COURT '+n+'</strong><span>'+label+'</span></div><div class="scs-court-teams"><div class="scs-court-team team-a">'+courtPlayerRows(g.pair1)+'</div><div class="scs-court-vs-line"><span></span><b>VS</b><span></span></div><div class="scs-court-team team-b">'+courtPlayerRows(g.pair2)+'</div></div>';
if(g.score)html+='<div class="scs-court-score">'+scoreText(g)+'</div>';if(st==='score_ready')html+='<button class="scs-court-approve" onclick="SCSCourtCenter.approve(\''+g.ccid+'\')">Approve &amp; Complete</button>';else html+='<button class="scs-court-view" onclick="SCSScoring.open()">Score ›</button>';if(notStarted(g))html+=matchActions(g);return html+'</div>'}
function render(){var body=el('scsCourtBody');if(!session){body.innerHTML='<div class="scs-court-start"><p>Start a Court Center for this club.</p><label>Number of courts <input id="scsCourtCount" type="number" min="1" max="20" value="2"></label><button onclick="SCSCourtCenter.start()">Start Court Center</button><button type="button" class="scs-court-tournament-entry" onclick="SCSCourtCenter.openTournament()">Create / Open Tournament</button></div>';el('scsCourtAssign').hidden=true;return}el('scsCourtAssign').hidden=false;var h='<div class="scs-court-tournament-actions"><button onclick="SCSCourtCenter.bracket(false)">Tournament bracket / Assign</button><button onclick="SCSCourtCenter.bracket(true)">Live bracket (read only)</button></div><div class="scs-court-grid">';for(var i=1;i<=courtCount();i++)h+=courtCard(i);h+='</div><div class="scs-court-tabs"><button class="'+(activeTab==='waiting'?'active':'')+'" onclick="SCSCourtCenter.tab(\'waiting\')">Waiting</button><button class="'+(activeTab==='completed'?'active':'')+'" onclick="SCSCourtCenter.tab(\'completed\')">Completed</button><button class="'+(activeTab==='ranking'?'active':'')+'" onclick="SCSCourtCenter.tab(\'ranking\')">Ranking</button></div><div class="scs-court-tabbody">'+tabHtml()+'</div>';body.innerHTML=h}
function tabHtml(){if(activeTab==='ranking')return rankingHtml();var list=games().filter(function(g){return activeTab==='waiting'?status(g)==='waiting':status(g)==='approved'});if(!list.length)return '<div class="scs-court-empty">No '+activeTab+' matches.</div>';return list.map(function(g,i){return '<div class="scs-court-row"><strong>'+(activeTab==='waiting'?'#'+(i+1):'✓')+' '+team(g,'pair1')+'</strong><span>vs</span><strong>'+team(g,'pair2')+'</strong>'+(activeTab==='completed'?'<em>'+scoreText(g)+'</em>':'')+(activeTab==='waiting'&&notStarted(g)?matchActions(g):'')+'</div>'}).join('')}
function rankingHtml(){var m={};games().filter(function(g){return status(g)==='approved'&&g.winner}).forEach(function(g){var win=g.winner==='L'?g.pair1:g.pair2,lose=g.winner==='L'?g.pair2:g.pair1;(g.pair1||[]).concat(g.pair2||[]).forEach(function(n){if(!m[n])m[n]={p:0,w:0,l:0};m[n].p++});win.forEach(function(n){m[n].w++});lose.forEach(function(n){m[n].l++})});var a=Object.keys(m).map(function(n){return{name:n,p:m[n].p,w:m[n].w,l:m[n].l}}).sort(function(a,b){return b.w-a.w||a.l-b.l||a.name.localeCompare(b.name)});if(!a.length)return '<div class="scs-court-empty">Ranking will appear after approved matches.</div>';return '<table class="scs-court-ranking"><thead><tr><th>#</th><th>Player</th><th>P</th><th>W</th><th>L</th></tr></thead><tbody>'+a.map(function(x,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(x.name)+'</td><td>'+x.p+'</td><td>'+x.w+'</td><td>'+x.l+'</td></tr>'}).join('')+'</tbody></table>'}
async function start(){try{await createSession();render()}catch(e){alert(e.message||'Could not start Court Center')}}
async function openTournament(){if(busy)return;busy=true;try{if(!session){session=await findSession();if(!session){await createSession();}}render();await bracket(false);}catch(e){alert(e.message||'Could not open tournament.');}finally{busy=false}}
function showAssign(editId){if(!session)return;editingId=typeof editId==='string'?editId:null;var current=editingId?games().find(function(g){return g.ccid===editingId}):null;if(editingId&&(!current||!notStarted(current))){alert('This match has already started.');return;}var used=new Set();games().filter(function(g){return status(g)!=='approved'&&g.ccid!==editingId}).forEach(function(g){(g.pair1||[]).concat(g.pair2||[]).forEach(function(n){used.add(String(n).toLowerCase())})});var opts='<option value="">Select player</option>'+players.filter(function(p){return p&&p.name&&!used.has(String(p.name).toLowerCase())}).map(function(p){return '<option value="'+esc(p.name)+'">'+esc(p.name)+'</option>'}).join('');el('scsCourtAssignForm').innerHTML='<h3>'+(editingId?'Change Players':pendingTournamentMatch?'Assign '+(session.rounds_data[0].tournament.title||'Mix-1')+' · Match '+pendingTournamentMatch:'Assign Match')+'</h3><div class="scs-court-selects"><label>Team A · Player 1<select>'+opts+'</select></label><label>Team A · Player 2<select>'+opts+'</select></label><div class="scs-court-vs">VS</div><label>Team B · Player 1<select>'+opts+'</select></label><label>Team B · Player 2<select>'+opts+'</select></label></div><div class="scs-court-form-actions"><button onclick="SCSCourtCenter.cancelAssign()">Cancel</button><button onclick="SCSCourtCenter.addMatch()">'+(editingId?'Save Changes':'Add Match')+'</button></div>';el('scsCourtAssignForm').hidden=false;Array.prototype.forEach.call(el('scsCourtAssignForm').querySelectorAll('select'),function(s){s.onchange=disableDupes});if(current){var ss=el('scsCourtAssignForm').querySelectorAll('select'),v=current.pair1.concat(current.pair2);Array.prototype.forEach.call(ss,function(sel,i){sel.value=v[i]||''});disableDupes()}}
function disableDupes(){var ss=Array.prototype.slice.call(el('scsCourtAssignForm').querySelectorAll('select')),vals=ss.map(function(s){return s.value}).filter(Boolean);ss.forEach(function(s){Array.prototype.forEach.call(s.options,function(o){o.disabled=!!o.value&&o.value!==s.value&&vals.indexOf(o.value)>=0})})}
function cancelAssign(){el('scsCourtAssignForm').hidden=true;editingId=null;pendingTournamentMatch=null}
async function latestSession(){if(isLocalSession()){var local=readLocalSession();if(!local)throw new Error('Local tournament session unavailable.');return local}var rows=await sbGet('sessions','id=eq.'+session.id+'&select=id,rounds_data,started_by,updated_at,club_id');if(!rows||!rows[0])throw new Error('Court Center session unavailable.');return rows[0]}
function occupiedNames(list,exceptId){var used=new Set();list.filter(function(g){return status(g)!=='approved'&&g.ccid!==exceptId}).forEach(function(g){(g.pair1||[]).concat(g.pair2||[]).forEach(function(n){used.add(String(n).toLowerCase())})});return used}
async function addMatch(){if(busy)return;var ss=Array.prototype.slice.call(el('scsCourtAssignForm').querySelectorAll('select')),v=ss.map(function(s){return s.value});if(v.some(function(x){return !x})||new Set(v).size!==4){alert('Select four different players.');return}if(pendingTournamentMatch){var tm=SCSTournament.matchInfo(pendingTournamentMatch);if(v.slice(0,2).join(' / ')!==tm.a||v.slice(2).join(' / ')!==tm.b){alert('Tournament match players must match the published bracket, in the same team order.');return}}busy=true;try{var fresh=await latestSession(),list=fresh.rounds_data[0].games||[],old=editingId?list.find(function(g){return g.ccid===editingId}):null;if(editingId&&(!old||!notStarted(old)))throw new Error('Match already started or was removed.');var used=occupiedNames(list,editingId);if(v.some(function(n){return used.has(n.toLowerCase())}))throw new Error('A selected player is already assigned to another match.');if(old){old.pair1=[v[0],v[1]];old.pair2=[v[2],v[3]];}else{list.push({ccid:'cc-'+Date.now(),tournament_match:pendingTournamentMatch||null,match_no:pendingTournamentMatch?(fresh.rounds_data[0].tournament.title||'Mix-1')+'-'+pendingTournamentMatch:null,pair1:[v[0],v[1]],pair2:[v[2],v[3]],winnerEnabled:true,court_center_status:'waiting',score:null,score_status:null,winner:null});}session=fresh;allocate();await save();cancelAssign();pendingTournamentMatch=null;render()}catch(e){alert(e.message||'Could not save match.');session=await latestSession().catch(function(){return session})}finally{busy=false}}
function editMatch(id){showAssign(id)}
async function deleteMatch(id){if(busy)return;var g=games().find(function(x){return x.ccid===id});if(!notStarted(g)){alert('This match has already started.');return}if(!confirm('Delete this match?'))return;busy=true;try{var fresh=await latestSession(),list=fresh.rounds_data[0].games||[],index=list.findIndex(function(x){return x.ccid===id});if(index<0||!notStarted(list[index]))throw new Error('Match already started or was removed.');list.splice(index,1);session=fresh;allocate();await save();render()}catch(e){alert(e.message||'Could not delete match.');session=await latestSession().catch(function(){return session})}finally{busy=false}}
async function approve(id){var g=games().find(function(x){return x.ccid===id});if(!g||g.score_status!=='scored')return;if(g.tournament_match){var t=session.rounds_data[0].tournament;if(!t)throw new Error('Tournament draw missing');SCSTournament.load(t);var m=SCSTournament.matchInfo(g.tournament_match),win=(g.winner==='L'?g.pair1:g.pair2).join(' / ');if(!g.winner||win!==m.a&&win!==m.b){alert('Choose a winner matching the tournament draw before approval.');return;}SCSTournament.approved(g.tournament_match,win);t.results[g.tournament_match]={winner:win,loser:win===m.a?m.b:m.a};}g.court_center_status='approved';var released=g.court;g.approved_at=new Date().toISOString();g.completed_court=released;g.court=null;if(!isLocalSession())allocate();await save();render()}
function tab(x){activeTab=x;render()}
async function changeTournamentCourts(delta){var local=readLocalSession();if(local)session=local;if(!isLocalSession())throw new Error('Open Tournament Live again to restore its local court session.');var round=session.rounds_data[0],old=courtCount(),next=Math.max(1,Math.min(20,old+Number(delta||0)));if(next<old&&games().some(function(g){return Number(g.court)>next&&g.court_center_status!=='approved'})){alert('Court '+old+' has an assigned match. Move or finish it before removing this court.');return null}round.numCourts=next;await save();return next}
async function startTournamentMatch(id){if(!session)session=readLocalSession();if(!isLocalSession())return false;var g=games().find(function(x){return Number(x.tournament_match)===Number(id)});if(!g||!g.court||g.court_center_status==='approved')return false;if(g.score_status==='scored')return false;g.started_at=g.started_at||new Date().toISOString();g.score_status='scoring';g.court_center_status='playing';await save();return true}
async function assignTournamentMatch(id,info,requestedCourt){if(busy||!info)return false;var local=readLocalSession();if(local)session=local;if(!session){alert('Start the tournament before assigning matches.');return false}var a=String(info.a||'').split(' / ').map(function(x){return x.trim()}).filter(Boolean),b=String(info.b||'').split(' / ').map(function(x){return x.trim()}).filter(Boolean),v=a.concat(b);if(a.length!==2||b.length!==2||new Set(v.map(function(x){return x.toLowerCase()})).size!==4){alert('Both teams need two distinct players.');return false}busy=true;try{var fresh=await latestSession(),round=fresh.rounds_data[0],list=round.games||[],g=list.find(function(x){return Number(x.tournament_match)===Number(id)});if(g&&(g.started_at||g.score||g.score_status||g.court_center_status==='approved'))throw new Error('This match has already started.');var court=Number(requestedCourt)||0;if(court<1||court>Number(round.numCourts))throw new Error('Invalid court.');var occupant=list.find(function(x){return Number(x.court)===court&&x.court_center_status!=='approved'&&x!==g});if(occupant&&(occupant.started_at||occupant.score||occupant.score_status))throw new Error('Cannot replace a match after scoring starts.');var used=occupiedNames(list,g&&g.ccid);if(occupant)(occupant.pair1||[]).concat(occupant.pair2||[]).forEach(function(n){used.delete(String(n).toLowerCase())});if(v.some(function(n){return used.has(n.toLowerCase())}))throw new Error('A player is already assigned to another active match.');if(occupant){occupant.court=null;occupant.court_center_status='waiting'}if(g){g.court=court;g.court_center_status='assigned'}else{list.push({ccid:'cc-'+Date.now(),tournament_match:id,match_no:(round.tournament&&round.tournament.title||'Tournament')+'-'+id,pair1:a,pair2:b,winnerEnabled:true,court:court,court_center_status:'assigned',score:null,score_status:null,winner:null})}session=fresh;await save();if(window.SCSTournament&&SCSTournament.renderLive)SCSTournament.renderLive();return true}catch(e){alert(e.message||'Could not assign tournament match.');session=await latestSession().catch(function(){return session});return false}finally{busy=false}}

async function bracket(ro){if(!session)return;try{session=await latestSession()}catch(e){}var round=session.rounds_data[0];if(!round.tournament){if(ro){alert('Set up the tournament in Court Center first.');return;}if(!confirm('Create a new tournament? Teams and match connections will be entered next.'))return;round.tournament=SCSTournament.init();try{await save()}catch(e){delete round.tournament;alert(e.message||'Could not save tournament');return;}}SCSTournament.open(round.tournament,ro,async function(updated){var fresh=await latestSession(),freshRound=fresh.rounds_data[0],previous=freshRound.tournament;freshRound.tournament=updated;session=fresh;try{await save();round=session.rounds_data[0]}catch(e){freshRound.tournament=previous;throw e}},function(id,info){assignTournamentMatch(id,info)},async function(){var fresh=await latestSession(),freshRound=fresh.rounds_data[0],previousTournament=freshRound.tournament,previousGames=(freshRound.games||[]).slice();freshRound.games=(freshRound.games||[]).filter(function(g){return !g.tournament_match});delete freshRound.tournament;session=fresh;try{await save();round=session.rounds_data[0]}catch(e){freshRound.tournament=previousTournament;freshRound.games=previousGames;throw e}});} 
async function openLiveBracket(){try{var fresh=await findSession();if(!fresh||!fresh.rounds_data||!fresh.rounds_data[0]||!fresh.rounds_data[0].tournament){alert('No live tournament bracket for your club.');return;}session=fresh;bracket(true)}catch(e){alert(e.message||'Could not load live tournament bracket')}}
function tournamentGame(id){return games().find(function(g){return Number(g.tournament_match)===Number(id)})}
window.SCSCourtCenter={startTournament:startTournament,resumeTournament:resumeTournament,liveState:liveState,refreshTournamentState:refreshTournamentState,freeCourts:freeCourts,playerNames:function(){return players.filter(function(p){return p&&p.name}).map(function(p){return p.name})},openLiveBracket:openLiveBracket,openTournament:openTournament,bracket:bracket,tournamentGame:tournamentGame,assignTournamentMatch:assignTournamentMatch,changeTournamentCourts:changeTournamentCourts,startTournamentMatch:startTournamentMatch,localScoreUpdate:localScoreUpdate,localSession:function(){return readLocalSession()},open:open,close:close,start:start,showAssign:showAssign,cancelAssign:cancelAssign,addMatch:addMatch,editMatch:editMatch,deleteMatch:deleteMatch,approve:approve,tab:tab,refresh:refresh};
})();
